<a href="https://colab.research.google.com/github/grismely/CSC448-AI/blob/main/Assignment%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


In [1]:
# Imports and pip installations (if needed)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import BayesianRidge
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import PolynomialFeatures as poly
from sklearn.model_selection import ShuffleSplit
from sklearn.datasets import load_iris
from sklearn import svm
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

# Part 1: Load the dataset

In [3]:
# Load the dataset (load remotely, not locally)
iris = load_iris()
iris_df = pd.DataFrame(iris['data'],columns = iris.feature_names)
iris_df["species"]= iris.target

# Output the first 15 rows of the data
iris_df.rename(columns = {'Sepal Length':'0'})
iris_df.head(15)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
5                 5.4               3.9                1.7               0.4   
6                 4.6               3.4                1.4               0.3   
7                 5.0               3.4                1.5               0.2   
8                 4.4               2.9                1.4               0.2   
9                 4.9               3.1                1.5               0.1   
10                5.4               3.7                1.5               0.2   
11                4.8               3.4                1.6               0.2   
12                4.8               3.0                1.4               0.1   
13                4.3               3.0                1.1               0.1   
14                5.8               4.0                1.2               0.2   

    species  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         0  
9         0  
10        0  
11        0  
12        0  
13        0  
14        0

In [4]:
# Display a summary of the table information (number of datapoints, etc.)
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

# Part 2: Split the dataset into train and test

In [5]:
# Take the dataset and split it into our features (X) and label (y)
features = iris_df[["sepal length (cm)","sepal width (cm)","petal length (cm)","petal width (cm)"]]
label = iris_df['species']
x, y = features, label

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.10)
x_train, x_test, y_train, y_test

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 46                 5.1               3.8                1.6               0.2
 48                 5.3               3.7                1.5               0.2
 14                 5.8               4.0                1.2               0.2
 129                7.2               3.0                5.8               1.6
 107                7.3               2.9                6.3               1.8
 ..                 ...               ...                ...               ...
 147                6.5               3.0                5.2               2.0
 110                6.5               3.2                5.1               2.0
 123                6.3               2.7                4.9               1.8
 61                 5.9               3.0                4.2               1.5
 25                 5.0               3.0                1.6               0.2
 
 [135 rows x 4 columns],
      sepal length (cm)  

# Part 3: Logistic Regression

In [6]:
# i. Use sklearn to train a LogisticRegression model on the training set
log_reg = LogisticRegression()
log_reg.fit(x_train,y_train)

/Users/grismelyhiraldo/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [7]:
# ii. For a sample datapoint, predict the probabilities for each possible class
log_reg.predict(np.array([[1,2,3,4]]))

array([2])

2 represents the iris species Virgincia 

In [8]:
# ii. For a sample datapoint, predict the probabilities for each possible class
log_reg.predict_proba(np.array([[1,2,3,4]]))

array([[0.05087456, 0.01731563, 0.93180981]])

In [24]:
# iii. Report on the score for Logistic regression model, what does the score measure?

In [9]:
log_reg.score(x_test,y_test)

0.9333333333333333

The score measures our chances(percentage) of classifying the flower correctly.

In [10]:
# iv. Extract the coefficents and intercepts for the boundary line(s)
print("Coeficients: ",log_reg.coef_)
print("Intercept: ",log_reg.intercept_)

Coeficients:  [[-0.38874095  0.92298196 -2.46174099 -1.06552264]
 [ 0.41614276 -0.31917987 -0.17721248 -0.8937092 ]
 [-0.02740181 -0.60380209  2.63895348  1.95923183]]
Intercept:  [  9.58008636   2.64093386 -12.22102022]


# Part 4: Support Vector Machine

In [11]:
# i. Use sklearn to train a Support Vector Classifier on the training set
svm_model = SVC(probability=True)
SVC.fit(svm_model,x_train,y_train)

SVC(probability=True)

In [12]:
# ii. For a sample datapoint, predict the probabilities for each possible class
svm_model.predict([[1,2,3,4]])

array([2])

In [13]:
# ii. For a sample datapoint, predict the probabilities for each possible class
svm_model.predict_proba([[1,2,3,4]])

array([[0.25617515, 0.22779141, 0.51603343]])

In [14]:
# iii. Report on the score for the SVM, what does the score measure?
svm_model.score(x_test,y_test)

0.9333333333333333

The score measures our chances(percentage) of classifying the flower correctly.

# Part 5: Neural Network

In [16]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set
mlp_model = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes =(15,), random_state=1).fit(features,label)
mlp_model.fit(x_train,y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
mlp_model.predict_proba([[1,2,3,4]])


array([[0.0000000e+00, 1.0630894e-10, 1.0000000e+00]])

In [17]:
# iii. Report on the score for the Neural Network, what does the score measure?
mlp_model.score(x_test,y_test)
# iv: Experiment with different options for the neural network, report on your best configuration (the highest score I was able to achieve was 0.8666)

1.0

The score measures our chances(percentage) of classifying the flower correctly.

# Part 6: K-Nearest Neighbors

In [20]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
kNN_model = KNeighborsClassifier(n_neighbors=5)
kNN_model.fit(x_train,y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
kNN_model.predict_proba([[1,2,3,4]])

array([[0. , 0.8, 0.2]])

In [21]:
# iii. Report on the score for kNN, what does the score measure?
kNN_model.score(x_test,y_test)

1.0

# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

The results of the notebook, in simple terms, was the percentage/chance of properly classifying the three different iris species. The dataset we used shows slight variety amongst petal length and width, as well as sepal length and width, the notebook and all the models used serve to create relationships between these differences and see how efficiently and accurately we can classify that data. For my particular code I think there was a mistake somwehere that I was not able to weed out, because all of my scores for the models were 1, I can cannot pick which one I think performed the best on the dataset--according to my results, they all did. Which, I know is very unlikely just based off the fact in class and in this template, the professor mentioned the best score they were able to obtain for one of the models was 0.866. Ultimately, I found the exercise farely interesting because it was a "practical" use of computer science, I've found that throughout my academic career we don't get too many "real-life" implementations so something as simple and pretty practical as comparing flower species was refreshing. Plus I do like irises.